create table SOLICITUD_NC(
SOL_ID SERIAL primary key,
SOL_FECHA_SOLICITUD DATE not null,
SOL_TIPO_NC VARCHAR(64) not null,
SOL_USUARIO_CREADOR INT not null,
SOL_FECHA_CREACION DATE NULL,
SOL_FECHA_MODIFICACION DATE NULL,
SOL_ESTADO VARCHAR(64) NULL,
SOL_OBSERVACION text NULL,
SOL_USUARIO_VALIDADOR INT null
);

create table DETALLE_SOLICITUD(
DET_ID SERIAL primary key,
DET_FECHA_EMISION DATE not null,
DET_NRO_COMPROBANTE VARCHAR(64) not null,
DET_IMPORTE_TOTAL FLOAT not null,
DET_MOTIVO VARCHAR(255) null,
DET_MONTO_TOTAL_PROD FLOAT null,
DET_ESTABLECIMIENTO INT null,
DET_DESCUENTO INT null,
DET_TOTAL_DESCUENTO FLOAT null,
DET_BOLETEO FLOAT null,
SDET_ID INT null,
DET_LABORA_EN VARCHAR(64) NULL
);

create table PRODUCTO_DETALLE(
DPRO_ID SERIAL primary key,
DPRO_CODIGO VARCHAR(7) not null,
DPRO_DESCRIPCION VARCHAR(255) not null,
DPRO_UNIDAD VARCHAR(32) not null,
DPRO_PRECIO FLOAT not null,
DPRO_CANTIDAD INT not null,
DPRO_MONTO_TOTAL FLOAT not NULL
);

create table SOLICITANTE_DET(
SDET_ID SERIAL primary key,
SDET_DNI VARCHAR(10) not NULL,
SDET_MATERNO VARCHAR(64) not null,
SDET_PATERNO VARCHAR(64) not null,
SDET_NOMBRES VARCHAR(64) not NULL
);

create table MARKET(
MAR_ID SERIAL primary key,
MAR_DESCRIPCION VARCHAR(64) not null
);


create table USUARIO(
USU_ID SERIAL primary key,
USU_NOMBRE VARCHAR(32) not null,
USU_CORREO VARCHAR(64) null,
MAR_ID INT null,
ROL_ID INT null
);

create table ROLES(
ROL_ID SERIAL primary key,
ROL_CODIGO VARCHAR(5) not null,
ROL_DESCRIPCION VARCHAR(32) not null
);

create table PERMISOS(
PER_ID SERIAL primary key,
PER_CODIGO VARCHAR(5) not null,
PER_DESCRIPCION VARCHAR(32) not null
);


create table ROLES_PERMISOS(
RPER_ID SERIAL primary key,
ROL_ID INT not null,
PER_ID INT not NULL
);

create table MENU(
MEN_ID SERIAL primary key,
MEN_DESCRIPCION VARCHAR(32) not NULL
);

create table MENU_RPERMISOS(
MERP_ID SERIAL primary key,
MEN_ID INT not null,
RPER_ID INT not null
);
